### ISSUE TITLE
no such element: Unable to locate element:

### ISSUE THREAD

**Issue by codeccpp** [anilabhadatta/educative.io_scraper#19]
Thanks for taking the time to create this great tool. Mostly, it's working just fine but sometimes I get the below error. Any idea on how I can fix it ? Thanks!

```
Take Screenshot Function
Found Issue, Going Next Course Message: no such element: Unable to locate element: {"method":"css selector","selector":"div[class*='ArticlePage']"}
  (Session info: headless chrome=106.0.5249.103)
Stacktrace:
Backtrace:
        Ordinal0 [0x01181ED3+2236115]
        Ordinal0 [0x011192F1+1807089]
        Ordinal0 [0x010266FD+812797]
        Ordinal0 [0x010555DF+1005023]
        Ordinal0 [0x010557CB+1005515]
        Ordinal0 [0x01087632+1209906]
        Ordinal0 [0x01071AD4+1120980]
        Ordinal0 [0x010859E2+1202658]
        Ordinal0 [0x010718A6+1120422]
        Ordinal0 [0x0104A73D+960317]
        Ordinal0 [0x0104B71F+964383]
        GetHandleVerifier [0x0142E7E2+2743074]
        GetHandleVerifier [0x014208D4+2685972]
        GetHandleVerifier [0x01212BAA+532202]
        GetHandleVerifier [0x01211990+527568]
        Ordinal0 [0x0112080C+1837068]
        Ordinal0 [0x01124CD8+1854680]
        Ordinal0 [0x01124DC5+1854917]
        Ordinal0 [0x0112ED64+1895780]
        BaseThreadInitThunk [0x76C9FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77067B5E+286]
        RtlGetAppContainerNamedObjectPath [0x77067B2E+238]
```

**Comment by anilabhadatta** [comment]
@codeccpp I need more information like topic URL, log data from terminal.

**Comment by anilabhadatta** [comment]
@codeccpp pull the repo again and test it, the selector should be fixed now.

**Comment by codeccpp** [comment]
@anilabhadatta alright, let me try.

**Comment by anilabhadatta** [comment]
@codeccpp pull v5.8.1

**Comment by codeccpp** [comment]
Didn't solve it. The url is: https://www.educative.io/courses/decode-coding-interview-cpp/qABQKQqWmmk

**Comment by anilabhadatta** [comment]
@codeccpp working at my end.

**Comment by codeccpp** [comment]
@anilabhadatta. Can you kindly send me the output from `pip3 list`. Also, can you zip your source directly and email it to me at codeccpp (at gmail.com)? Thanks!

**Comment by anilabhadatta** [comment]
@codeccpp the requirements are already provided in GitHub repo

**Comment by anilabhadatta** [comment]
![image](https://user-images.githubusercontent.com/48487849/195896318-eaf1dabf-186b-4f12-a2ee-b4fe89ee2d3e.png)

try cloning again, also there is an issue with file naming for this topic which I will fix it tonight

**Comment by codeccpp** [comment]
@anilabhadatta Apparently, the error had to do with long file names. I put it in a shorter directory and it works now.

**Comment by anilabhadatta** [comment]
@codeccpp yes most probably long file names, I will fix the file naming issue today.

**Comment by anilabhadatta** [comment]
@codeccpp pull the latest repo and do some testing, should fix the file naming issues.
Also you can enable long path
https://www.microfocus.com/documentation/filr/filr-4/filr-desktop/t47bx2ogpfz7.html

**Comment by paletisuresh** [comment]
Getting below error any help is greatly appreciated.

Driver Loaded

                            [Selected config: 0] Starting Scraping: 0, https://www.educative.io/courses/decode-coding-interview-cpp/qABQKQqWmmk

Load Webpage Function
Checking Login Function
Checking for captcha Function...
Create Course Folder Function
Found Issue, Going Next Course Message: no such element: Unable to locate element: {"method":"css selector","selector":"h4"}
  (Session info: headless chrome=96.0.4664.110)
Stacktrace:
Backtrace:
        Ordinal0 [0x00A56903+2517251]
        Ordinal0 [0x009EF8E1+2095329]
        Ordinal0 [0x008F2848+1058888]
        Ordinal0 [0x0091D448+1233992]
        Ordinal0 [0x0091D63B+1234491]
        Ordinal0 [0x00913AB1+1194673]
        Ordinal0 [0x0093650A+1336586]
        Ordinal0 [0x00913A36+1194550]
        Ordinal0 [0x009365BA+1336762]
        Ordinal0 [0x00945BBF+1399743]
        Ordinal0 [0x0093639B+1336219]
        Ordinal0 [0x009127A7+1189799]
        Ordinal0 [0x00913609+1193481]
        GetHandleVerifier [0x00BE5904+1577972]
        GetHandleVerifier [0x00C90B97+2279047]
        GetHandleVerifier [0x00AE6D09+534521]
        GetHandleVerifier [0x00AE5DB9+530601]
        Ordinal0 [0x009F4FF9+2117625]
        Ordinal0 [0x009F98A8+2136232]
        Ordinal0 [0x009F99E2+2136546]
        Ordinal0 [0x00A03541+2176321]
        BaseThreadInitThunk [0x769FFA29+25]
        RtlGetAppContainerNamedObjectPath [0x775E7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x775E7B8E+238]

**Comment by anilabhadatta** [comment]
@paletisuresh clone the repo and use the tool.
Steps are provided in readme.
Avoid using releases executable file as they are not updated

**Comment by anilabhadatta** [comment]
@codeccpp @paletisuresh closing this issue since file naming was fixed in latest version.
